[package]
name = "nexnex"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.16", default-features = false, features = [
    "bevy_sprite",
    "bevy_winit",
    "bevy_core_pipeline",
    "png",
] }
bevy_ecs_ldtk = "0.12"
bevy_rapier2d = "0.30"
