[package]
name = "nexnex"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13"
bevy_ecs_ldtk = { git = "https://github.com/Trouv/bevy_ecs_ldtk" }

[patch.crates-io]
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap/", branch = "main" }
