name: Deploy Platformer JS to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'platformer_js/**'
      - '.github/workflows/deploy-platformer.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-platformer"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: platformer_js
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: platformer_js/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm run test:run
        
      - name: Build project
        run: npm run build
        
      - name: Build documentation
        run: npm run build:docs
        
      - name: Prepare deployment directory
        run: |
          mkdir -p ../deploy/platformer
          cp -r dist/* ../deploy/platformer/
          cp -r docs ../deploy/platformer/
          cp index.html ../deploy/platformer/
          cp -r assets ../deploy/platformer/
          cp -r src ../deploy/platformer/
          cp styles.css ../deploy/platformer/
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './deploy'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}platformer/
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4